version: '3'
services:
  web:
    depends_on:
      - db
    #image: emedic/webserver-m2:1.0.0
    image: emedic/magento-base:1.0.0
    #build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - webdata:/var/www/html
  db:
    image: mariadb:10.1.13
    ports:
      - "8006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'eMedic!dev'
      MYSQL_DATABASE: magento
      MYSQL_USER: emedidba
      MYSQL_PASSWORD: 'eMedic!dev'
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
  setup:
    image: emedic/webserver-m2:1.0.0
    depends_on:
      - db
    volumes:
      - webdata:/var/www/html
    environment:
      M2SETUP_DB_HOST: db
      M2SETUP_DB_NAME: "magento"
      M2SETUP_DB_USER: "emedidba"
      M2SETUP_DB_PASSWORD: 'eMedic!dev'
      M2SETUP_BASE_URL: "http://magelocal/"
      M2SETUP_ADMIN_FIRSTNAME: "Admin"
      M2SETUP_ADMIN_LASTNAME: "User"
      M2SETUP_ADMIN_EMAIL: "dummy@email.com"
      M2SETUP_ADMIN_USER: "magento2"
      M2SETUP_ADMIN_PASSWORD: "eMedic2013"
      USE_SECURE: "0"
      M2SETUP_BASE_URL_SECURE: "https://magelocal/"
      USE_SECURE_ADMIN: "0"
volumes:
  dbdata:
  webdata:
