name: Build Docker Image
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    env: 
      mage_filesystem_s3_url: "s3://beracah-cicd/magento-2019-03-14_16-51.tar.gz"
    steps:
      - name: Download AWS s3 file 
        run: echo $MAGE_FILESYSTEM_S3_URL
      
