name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    env: 
      DOCKER_HUB_USER: ${{ secrets.EDGAR_DOCKER_HUB_USER}}
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: print-env
        run: echo $DOCKER_HUB_USER
